spring:
  application:
    name: stock
  datasource:
    url: jdbc:postgresql://104.154.190.156/stock?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: macc
    password: 1234qwer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
